-- BETWEEN
-- ENTRE O MINIMO E O MÁXIMO

-- T0DOS QUE ESTÃO FORA DO VALOR SOLICITADO DEVIDO O "NOT";

SELECT ListPrice
FROM Production.Product
WHERE ListPrice NOT BETWEEN 1000 AND 1200;

-- TODOS QUE FORAM CONTRATADO DENTRO DE UM PERIODO;

SELECT HireDate, LoginID, JobTitle, Gender
FROM HumanResources.Employee
WHERE HireDate BETWEEN '2009/01/01' AND '2010/01/01'
ORDER BY HireDate